Repository PasteUs/PasteMeGoBackend, pull requests merged in 2020-08, with the labels that each got.

#67 Log to file
  .gitignore
  config.example.json
  config/config.go
  go.mod
  go.sum
  middleware/middleware.go
  server/server.go
Labels: enhancement

#73 Add version validator
  .gitignore
  config.example.json
  config/config.go
  doc/API.md
  flag/flag.go
  go.mod
  go.sum
  main.go
  meta/meta.go
  middleware/middleware.go
  server/server.go
Labels: enhancement

#75 Migrate docs to docs.pasteme.cn, update dockerfile, add docker-entrypoint.sh
  .github/config/config.mysql.json
  .github/config/config.sqlite3.json
  .github/workflows/dev.yml
  .github/workflows/master.yml
  .github/workflows/test.yml
  .github/workflows/upload-to-release.yml
  Dockerfile
  README.md
  config.example.json
  doc/API.md
  doc/CHANGELOG.md
  doc/DEPLOY.md
  doc/MIGRATE.md
  docker-compose.yml
  docker-entrypoint.sh
Labels: documentation, enhancement

#77 Fix/dockerfile
  Dockerfile
  docker-entrypoint.sh
Labels: bug

#78 merge dev to master
  .github/config/config.mysql.json
  .github/config/config.sqlite3.json
  .github/workflows/dev.yml
  .github/workflows/master.yml
  .github/workflows/test.yml
  .github/workflows/upload-to-release.yml
  .gitignore
  Dockerfile
  README.md
  config.example.json
  config/config.go
  doc/API.md
  doc/CHANGELOG.md
  doc/DEPLOY.md
  doc/MIGRATE.md
  docker-compose.yml
  docker-entrypoint.sh
  flag/flag.go
  go.mod
  go.sum
  main.go
  meta/meta.go
  server/server.go
Labels: chore
